// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hC3qXCD25ZBRmtPLiXzDz3eYDEZCFCs',
    appId: '1:36771286308:web:942ecdd9c73793815cf7b1',
    messagingSenderId: '36771286308',
    projectId: 'ride-card-app',
    authDomain: 'ride-card-app.firebaseapp.com',
    storageBucket: 'ride-card-app.appspot.com',
    measurementId: 'G-BWJB95Z1S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9jXPJt76tQPR3M6dPjEOtgeqzhVpO-hk',
    appId: '1:36771286308:android:69d501bcfa3f8fcb5cf7b1',
    messagingSenderId: '36771286308',
    projectId: 'ride-card-app',
    storageBucket: 'ride-card-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPmhEeB4mPAYXI9E4Fq7uwIgcoMRIIxvQ',
    appId: '1:36771286308:ios:4843ba77606e6aa25cf7b1',
    messagingSenderId: '36771286308',
    projectId: 'ride-card-app',
    storageBucket: 'ride-card-app.appspot.com',
    iosBundleId: 'com.example.rideCardApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPmhEeB4mPAYXI9E4Fq7uwIgcoMRIIxvQ',
    appId: '1:36771286308:ios:67748df0125d56f65cf7b1',
    messagingSenderId: '36771286308',
    projectId: 'ride-card-app',
    storageBucket: 'ride-card-app.appspot.com',
    iosBundleId: 'com.example.rideCardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1hC3qXCD25ZBRmtPLiXzDz3eYDEZCFCs',
    appId: '1:36771286308:web:40aeb799aeed4eac5cf7b1',
    messagingSenderId: '36771286308',
    projectId: 'ride-card-app',
    authDomain: 'ride-card-app.firebaseapp.com',
    storageBucket: 'ride-card-app.appspot.com',
    measurementId: 'G-EKTC2LNZMZ',
  );
}
